# Site Settings
title: Blog de Cédric Temple
author: Cédric Temple
# email: 
description: Blog sur l'administration système sur GNU/Linux, les logiciels libres, la supervision ...
about: Administrateur système en logiciels libres
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.cedrictemple.net" # the base hostname & protocol for your site
google_analytics: "UA-44206578-1"


# These can be '' to hide the Github or Gitlab nav buttons
github: ''
gitlab: ''

enableTags: true
tagarray: []

# Social Media
# Remove the item if you don't need it
# github_username: github_username
# facebook_username: facebook_username
twitter_username: Cedric_Temple
avatar_url: /static/img/avatar.jpg
#instagram_username: instagram_username
#linkedin_username: linkedin_username
#medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 20
per_page: 20

toc:
  min_level: 1
  max_level: 6
  no_toc_section_class: no_toc_section
  list_class: section-nav
  sublist_class: ''
  item_class: toc-entry
  item_prefix: toc-

# Plugins
plugins_dir:
  - jemoji
  - jekyll-paginate
  - jekyll-gist
  - jekyll-toc

collections:
  notes-pour-plus-tard:
    output: true

# Links to include in menu navigation
# For external links add external: true
urls:
  - text: À propos
    url: /a-propos/
  - text: Contact et informations légales
    url: /contact-et-informations-legales/
  - text: Articles par tags
    url: /tags/
  - text: Flux RSS
    url: /feed.xml

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules', '_drafts', '*.sh']

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  # endings: all
  blanklines: false
  profile: false
  ignore:
    envs: ['development']
